# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_organization_organization_code_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="step",
            constraint=models.UniqueConstraint(
                fields=("recipe", "order"),
                name="unique_step_order_per_recipe",
            ),
        ),
    ]
